$(document).ready(function(){
	$("#BgImDiv").hide();
	$("#BgClrDiv").hide();
	$("#TxtClrDiv").hide();
	$("#BmTabDiv").hide();
	$("#Tip1Div").hide();
	$("#Tip2Div").hide();
	$("#Tip3Div").hide();
	$("#Tip4Div").hide();
	$("#Tip5Div").hide();
	$("#Tip6Div").hide();
	$("#CreditDiv").hide();
	$("#BgImBttn").click(function(){
		$("#BgImDiv").slideToggle("800");
	});
	$("#BgClrBttn").click(function(){
		$("#BgClrDiv").slideToggle("800");
	});
	$("#TxtClrBttn").click(function(){
		$("#TxtClrDiv").slideToggle("800");
	});
	$("#BmTabBttn").click(function(){
		$("#BmTabDiv").slideToggle("800");
	});
	$("#Tip1Bttn").click(function(){
		$("#Tip1Div").slideToggle("800");
	});
	$("#Tip2Bttn").click(function(){
		$("#Tip2Div").slideToggle("800");
	});
	$("#Tip3Bttn").click(function(){
		$("#Tip3Div").slideToggle("800");
	});
	$("#Tip4Bttn").click(function(){
		$("#Tip4Div").slideToggle("800");
	});
	$("#Tip5Bttn").click(function(){
		$("#Tip5Div").slideToggle("800");
	});
	$("#Tip6Bttn").click(function(){
		$("#Tip6Div").slideToggle("800");
	});
	$("#CreditBttn").click(function(){
		$("#CreditDiv").slideToggle("800");
	});
});
